{{- if and .Values.manila .Values.manila.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-manila
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: manila
  namespace: {{ .Values.cluster.namespace | default "argocd" | quote }}
  annotations:
  {{- toYaml .Values.notifications | nindent 4 }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url }}
    namespace: manila-csi
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  source:
    repoURL: https://kubernetes.github.io/cloud-provider-openstack
    chart: openstack-manila-csi
    targetRevision: {{ .Values.manila.version | quote }}
    helm:
      version: v3
      releaseName: manila-csi
      values: |
        secret:
          enabled: true
          create: true
          name: manila-csi-cloud-config
          data:
            cloud.conf: |-
              [Global]
              auth-url={{ .Values.openstack.auth_url }}
              region={{ .Values.openstack.region }}
              application-credential-id={{ .Values.openstack.credential_id }}
              application-credential-secret={{ .Values.openstack.credential_secret }}
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
{{- end }}
